name: Sync Branch

on:
  workflow_call:
    inputs:
      base_branch:
        description: 'The base branch to sync from'
        required: true
        default: 'main'
        type: string
      target_branch:
        description: 'The target branch to sync to'
        required: true
        default: 'dev'
        type: string
      reviewers:
        description: 'Comma-separated list of reviewers'
        required: false
        default: ''
        type: string

permissions: {}

jobs:
  create_pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 https://github.com/actions/checkout/releases/tag/v6.0.2
        with:
          fetch-depth: 0

      - name: Check for commits in base branch but not in target branch
        id: check_commits
        env:
          BASE_BRANCH: ${{ inputs.base_branch }}
          TARGET_BRANCH: ${{ inputs.target_branch }}
        run: |
          echo "Checking for commits in $BASE_BRANCH that are not in $TARGET_BRANCH..."

          new_commits=$(git log "origin/$BASE_BRANCH" --not "origin/$TARGET_BRANCH" --oneline)

          if [ -z "$new_commits" ]; then
            echo "No unique commits found in $BASE_BRANCH that are not in $TARGET_BRANCH."
            echo "no_diff=true" >> $GITHUB_ENV
          else
            echo "Unique commits in $BASE_BRANCH that are not in $TARGET_BRANCH:"
            echo "$new_commits"
            echo "no_diff=false" >> $GITHUB_ENV
          fi

      - name: Check for existing PR and create if not exists
        if: env.no_diff == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ inputs.base_branch }}
          TARGET_BRANCH: ${{ inputs.target_branch }}
          REVIEWERS: ${{ inputs.reviewers }}
          REPO: ${{ github.repository }}
        run: |
          pr_exists=$(gh pr list --base "$TARGET_BRANCH" --head "$BASE_BRANCH" --repo "$REPO" --json number --jq '.[0].number')

          if [ -n "$pr_exists" ]; then
            echo "A pull request already exists: #$pr_exists"
          else
            gh pr create --base "$TARGET_BRANCH" \
            --head "$BASE_BRANCH" \
            --title "Sync from $BASE_BRANCH to $TARGET_BRANCH" \
            --body "This PR synchronizes changes from $BASE_BRANCH to $TARGET_BRANCH." \
            --repo "$REPO" \
            --reviewer "$REVIEWERS"

            echo "Pull request created successfully."
          fi
