name: Reusable Release Workflow

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string
      description:
        description: 'Release description'
        required: true
        type: string
      prerelease:
        description: 'Whether prerelease is enabled'
        required: true
        type: boolean
      changelog_path:
        description: 'The filepath of the changelog file'
        required: false
        type: string
        default: ""
      build_command:
        description: 'Command to build from source'
        required: false
        type: string
        default: ""
      docker_image_name:
        description: 'Full Docker image reference'
        required: false
        type: string
        default: ""
      docker_image_table_template:
        description: 'Template for the Docker image section'
        required: false
        type: string
        default: ""
      dependencies_template:
        description: 'List of dependencies'
        required: false
        type: string
        default: ""

permissions: {}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Generate base release notes
        env:
          DESCRIPTION: ${{ inputs.description }}
        run: |
          tee release_notes.md <<EOF
          # 🚀 Overview

          $DESCRIPTION
          EOF

      - name: Append changelog section (if enabled)
        if: inputs.changelog_path
        env:
          CHANGELOG_PATH: ${{ inputs.changelog_path }}
        run: |
          tee -a release_notes.md <<EOF

          # 📄 Changelog

          You can view the complete changelog [here]($CHANGELOG_PATH)
          EOF

      - name: Append Build from Source section (if enabled)
        if: inputs.build_command
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ inputs.tag }}
          BUILD_COMMAND: ${{ inputs.build_command }}
        run: |
          REPO_NAME=$(basename "$REPO")
          tee -a release_notes.md <<EOF

          # 🏗️ Binaries

          If you prefer to build from source, use the following commands:

          \`\`\`sh
          git clone https://github.com/${REPO}.git
          cd ${REPO_NAME}
          git checkout ${TAG}
          ${BUILD_COMMAND}
          \`\`\`
          EOF

      - name: Append Docker Image section (if enabled)
        if: inputs.docker_image_name || inputs.docker_image_table_template
        env:
          DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
          DOCKER_IMAGE_TABLE: ${{ inputs.docker_image_table_template }}
        run: |
          if [[ -z "$DOCKER_IMAGE_TABLE" ]]; then
            tee -a release_notes.md <<EOF

          # 🐳 Docker Image

          | Image | Description |
          |---------------|----------------|
          | \`${DOCKER_IMAGE_NAME}\` | Official release image |
          EOF
          else
            tee -a release_notes.md <<EOF
          # 🐳 Docker Image
          ${DOCKER_IMAGE_TABLE}
          EOF
          fi

      - name: Append Dependencies (if enabled)
        if: inputs.dependencies_template
        env:
          DEPENDENCIES: ${{ inputs.dependencies_template }}
        run: |
          tee -a release_notes.md <<EOF

          # 📦 Dependencies

          $DEPENDENCIES
          EOF

      - name: Create GitHub release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1 https://github.com/softprops/action-gh-release/releases/tag/v2.6.1
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          body_path: release_notes.md
          draft: false
          prerelease: ${{ inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
