# adapted from https://github.com/osmosis-labs/osmosis/blob/main/.goreleaser.yaml
name: Changelog Reminder
on:
  workflow_call:
    inputs:
      run-changelog-check:
        description: 'Run changelog check'
        type: boolean
        default: true

jobs:
  check_changelog:
    name: Check Changelogs
    runs-on: ubuntu-24.04
    if: ${{ inputs.run-changelog-check }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.0
        with:
          files_ignore: |
            **/*.md
            **/*_test.go
            tests/**
            **/*.py
            .github/workflows/*.yml

      - name: Changelog check
        # Skip this step and return success result for markdown only changes
        if: |
          steps.changed-files.outputs.any_changed == 'true' ||
          steps.changed-files.outputs.any_deleted == 'true' ||
          steps.changed-files.outputs.any_modified == 'true'
        uses: Zomzog/changelog-checker@v1.3.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: A:no-changelog
          checkNotification: Simple
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
